INSERT INTO names (first_name, last_name)
VALUES
('Brandon', 'Laursen'),
('Maica', 'Santos'),
('Trevor', 'Moore'),
('Charles', 'Woods'),
('Shane', 'Wilkey'),
('Briana', 'Robinson'),
('Charlie', 'Sheppard'),
('Gary', 'Song'),
('Geoffrey', 'Otieno'),
('Tanner', 'Shaw'),
('Daniel', 'Chin'),
('Anthony', 'Lovern'),
('Jojo', 'Yih'),
('Franco', 'Portin'),
('Dan', 'Purcell'),
('Keegan', 'Abley'),
('Jefferson', 'Garcia'),
('Brad', 'Simpson'),
('David', 'Nash'),
('Andrew', 'Tran'),
('Hector', 'Crespo'),
('Brian', 'Kiesel');